name: test workflow

on: [push]

env:
  PREVIEW: false
  PROD: true
  TEST: 'this is a test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world!
        run: echo "Hello world from github actions! 🚀"

      - name: test ${{ env.TEST }}
        run: echo ${{ env.TEST }}

      - name: test ${{ env.PREVIEW }}
        run: echo ${{ env.PREVIEW }}

      - name: test ${{ env.PROD }}
        run: echo ${{ env.PROD }}

      - name: Deploy to..
        run: echo netlify deploy --prod ${{ env.PROD }} --build --site ${{ vars.NETLIFY_SITE_ID }} --message "${{ github.ref_name }} >> ${{ github.event.head_commit.message }}"  --alias=${{ github.ref_name }}

