name: test workflow

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: netlify-cli  help
        run: netlify --help

      - name: netlify-cli which
        run: which netlify

