name: test workflow

on: [push]

env:
  COUNTRY_CODE: ${{ vars.COUNTRY_CODE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world!
        run: echo "Hello world from github actions! 🚀"
      - name: print env vars
        run: echo COUNTRYCODE=$COUNTRY_CODE

