name: test workflow

on: [push]

env:
  PREVIEW: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world!
        run: echo "Hello world from github actions! 🚀"
        
      - name: Deploy to..
        run: echo netlify deploy --prod ${{ !env.PREVIEW }} --build --site ${{ vars.NETLIFY_SITE_ID }} --message "${{ github.ref_name }} >> ${{ github.event.head_commit.message }}"  --alias=${{ github.ref_name }}

